services:
  postgres:
    image: postgres:16-alpine
    container_name: prontuario-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: prontuario
      POSTGRES_PASSWORD: prontuario123
      POSTGRES_DB: prontuario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
